/** Shared paths and environment for the SchemaForge e2e suite. */
import crypto from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const E2E_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const REPO_ROOT = path.resolve(E2E_ROOT, '..');
export const MCP_SRC = path.join(REPO_ROOT, 'mcp-server', 'src');
export const ENV_FILE = path.join(E2E_ROOT, '.env.e2e.local');
export const TMP_DIR = path.join(E2E_ROOT, '.tmp');

/** Local demo credentials, as published in config/*.env.example and docker-compose.yml. */
const DEFAULTS: Record<string, string> = {
  E2E_PROD_READONLY_URL: 'postgresql://sf_reader:sf_reader_pass@127.0.0.1:5433/schemaforge_prod',
  E2E_PROD_WRITE_URL: 'postgresql://sf_executor:sf_executor_pass@127.0.0.1:5433/schemaforge_prod',
  E2E_PROD_ADMIN_URL: 'postgresql://sf_admin:sf_admin_pass@127.0.0.1:5433/schemaforge_prod',
  E2E_SHADOW_URL: 'postgresql://sf_shadow:sf_shadow_pass@127.0.0.1:5434/schemaforge_shadow',
  E2E_CORE_PORT: '3200',
  E2E_EXECUTOR_PORT: '3201',
  SF_E2E_REQUIRE_DB: '0',
};

function parse(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of text.split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    // Skip placeholder values such as <password>.
    if (match && !match[2].includes('<')) out[match[1]] = match[2];
  }
  return out;
}

export type E2EEnv = Record<string, string>;

export function readEnv(): E2EEnv {
  const file = existsSync(ENV_FILE) ? parse(readFileSync(ENV_FILE, 'utf8')) : {};
  return { ...DEFAULTS, ...file };
}

/** Keep user overrides, but always mint a fresh random approval secret for this run. */
export function writeRunEnv(extra: Record<string, string>): E2EEnv {
  const env: E2EEnv = {
    ...readEnv(),
    ...extra,
    SF_APPROVAL_SECRET: crypto.randomBytes(48).toString('base64url'),
  };
  const body = Object.entries(env)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');
  writeFileSync(ENV_FILE, `# Generated by e2e/support/global-setup.ts. Git-ignored. Do not commit.\n${body}\n`);
  return env;
}

/** Process env with every SF_* / E2E_* variable stripped so nothing leaks between roles. */
export function cleanProcessEnv(): NodeJS.ProcessEnv {
  const base: NodeJS.ProcessEnv = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (!key.startsWith('SF_') && !key.startsWith('E2E_')) base[key] = value;
  }
  return base;
}

export function coreEnv(env: E2EEnv): NodeJS.ProcessEnv {
  return {
    ...cleanProcessEnv(),
    SF_PROD_READONLY_URL: env.E2E_PROD_READONLY_URL,
    SF_SHADOW_URL: env.E2E_SHADOW_URL,
    SF_HTTP_HOST: '127.0.0.1',
    SF_CORE_PORT: env.E2E_CORE_PORT,
    SF_TARGET_ID: 'prod',
  };
}

export function executorEnv(env: E2EEnv): NodeJS.ProcessEnv {
  return {
    ...cleanProcessEnv(),
    SF_PROD_READONLY_URL: env.E2E_PROD_READONLY_URL,
    SF_PROD_WRITE_URL: env.E2E_PROD_WRITE_URL,
    SF_APPROVAL_SECRET: env.SF_APPROVAL_SECRET,
    SF_HTTP_HOST: '127.0.0.1',
    SF_EXECUTOR_PORT: env.E2E_EXECUTOR_PORT,
    SF_APPROVAL_TTL_SECONDS: '300',
    SF_TARGET_ID: 'prod',
  };
}

/** Env for the human approval CLI: only the secret and TTL. */
export function cliEnv(env: E2EEnv): NodeJS.ProcessEnv {
  return {
    ...cleanProcessEnv(),
    SF_APPROVAL_SECRET: env.SF_APPROVAL_SECRET,
    SF_APPROVAL_TTL_SECONDS: '300',
  };
}
